container:
  image: bigtruedata/sbt:latest

#test_task:
#  env:
#    matrix:
#      TRAVIS_SCALA_VERSION: 2.12.3
#      TRAVIS_SCALA_VERSION: 2.11.11
#    matrix:
#      TEST_TARGET: "scalding-args scalding-date maple scalding-quotation"
#      TEST_TARGET: "scalding-avro scalding-hraven scalding-commons scalding-parquet scalding-parquet-scrooge"
#      TEST_TARGET: "scalding-core scalding-jdbc scalding-json scalding-db"
#      TEST_TARGET: "scalding-hadoop-test"
#      TEST_TARGET: "scalding-estimators-test"
#      TEST_TARGET: "scalding-serialization scalding-spark"
#      TEST_TARGET: "scalding-thrift-macros"
#  scalding_cache:
#    folder: $HOME/.scalding.dep.cache
#    fingerprint_script: echo $TRAVIS_SCALA_VERSION $TEST_TARGET
#  test_script: scripts/run_test.sh

task:
  name: test tuttorials and repl
  env:
    TEST_TARGET: "scalding-repl"
    matrix:
      TRAVIS_SCALA_VERSION: 2.12.3
      TRAVIS_SCALA_VERSION: 2.11.11
  scalding_cache:
    folder: $HOME/.scalding.dep.cache
    fingerprint_script: echo $TRAVIS_SCALA_VERSION
  test_script:
    - scripts/run_test.sh
    - scripts/build_assembly_no_test.sh scalding-assembly
    - scripts/test_tutorials.sh
    - scripts/build_assembly_no_test.sh scalding-assembly
    - scripts/test_matrix_tutorials.sh

task:
  name: test repl and typed tutorials and microsite
  env:
    matrix:
      TRAVIS_SCALA_VERSION: 2.12.3
      TRAVIS_SCALA_VERSION: 2.11.11
  scalding_cache:
    folder: $HOME/.scalding.dep.cache
    fingerprint_script: echo $TRAVIS_SCALA_VERSION
  install_jekyll_script:
    - apt-get update
    - apt-get install -y ruby ruby-dev build-essential
    - echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
    - echo 'export GEM_HOME=$HOME/gems' >> ~/.bashrc
    - echo 'export PATH=$HOME/gems/bin:$PATH' >> ~/.bashrc
    - gem install jekyll bundler
  test_script:
    - ./sbt ++$TRAVIS_SCALA_VERSION clean docs/makeMicrosite
    - scripts/build_assembly_no_test.sh scalding-repl
    - scripts/test_repl_tutorial.sh
    - scripts/build_assembly_no_test.sh scalding-core
    - scripts/test_typed_tutorials.sh
    - scripts/build_assembly_no_test.sh execution-tutorial
    - scripts/test_execution_tutorial.sh